create table account (ACC_ID integer not null auto_increment, ACC_LABEL varchar(32) not null unique, ACC_QUOTA bigint, ACC_CONSUMED_SMS bigint not null, primary key (ACC_ID)) ENGINE=InnoDB;
create table application (APP_ID integer not null auto_increment, APP_NAME varchar(32) not null unique, APP_CERTIFCATE blob, APP_QUOTA bigint not null, APP_CONSUMED_SMS bigint not null, ACC_ID integer not null, INS_ID integer not null, primary key (APP_ID)) ENGINE=InnoDB;
create table blacklist (BLA_ID integer not null auto_increment, BLA_DATE datetime not null, BLA_PHONE varchar(255) not null unique, APP_ID integer not null, primary key (BLA_ID)) ENGINE=InnoDB;
create table institution (INS_ID integer not null auto_increment, INS_LABEL varchar(32) not null unique, primary key (INS_ID)) ENGINE=InnoDB;
create table sms (SMS_ID integer not null auto_increment, SMS_INITIAL_ID integer, SMS_SENDER_ID integer, BROKER_SMS_ID integer, SMS_STATE varchar(32) not null, SMS_DATE datetime not null, SMS_PHONE varchar(255), APP_ID integer not null, ACC_ID integer not null, primary key (SMS_ID)) ENGINE=InnoDB;
create table statistic (APP_ID integer not null, ACC_ID integer not null, STAT_MONTH date not null, STAT_NB_SMS bigint not null, STAT_NB_SMS_IN_ERROR bigint not null, primary key (APP_ID, ACC_ID, STAT_MONTH)) ENGINE=InnoDB;
alter table application add index FK5CA40550173096CF (INS_ID), add constraint FK5CA40550173096CF foreign key (INS_ID) references institution (INS_ID);
alter table application add index FK5CA4055018242B51 (ACC_ID), add constraint FK5CA4055018242B51 foreign key (ACC_ID) references account (ACC_ID);
alter table blacklist add index FK4F74291D311F0354 (APP_ID), add constraint FK4F74291D311F0354 foreign key (APP_ID) references application (APP_ID);
alter table sms add index FK1BD59311F0354 (APP_ID), add constraint FK1BD59311F0354 foreign key (APP_ID) references application (APP_ID);
alter table sms add index FK1BD5918242B51 (ACC_ID), add constraint FK1BD5918242B51 foreign key (ACC_ID) references account (ACC_ID);
alter table statistic add index FK83F27950311F0354 (APP_ID), add constraint FK83F27950311F0354 foreign key (APP_ID) references application (APP_ID);
alter table statistic add index FK83F2795018242B51 (ACC_ID), add constraint FK83F2795018242B51 foreign key (ACC_ID) references account (ACC_ID);
